language: node_js
node_js:
  - "8"
before_script:
  - cd packages/a && npm i && cd ../../
  - cd packages/b && npm i && cd ../../
script:
  - npm run cover
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
